 server:
  port: 8083

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true



# service-url : used to locate the Eureka server
# fetch-registry : controls whether or not this client is going to try to connect to the Eureka server(s)
#                  in order to download the information on other service
# register-with-eureka :controls whether or not this client registers itself and therefore becomes discoverable
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

