server:
  port: 8761

spring:
  application:
    name: eureka-server

# service-url : used to locate the Eureka server
# fetch-registry : controls whether or not this client is going to try to connect to the Eureka server(s)
#                  in order to download the information on other service
# register-with-eureka :controls whether or not this client registers itself and therefore becomes discoverable
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false


